# Generated by Django 3.2.25 on 2024-03-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/abroman/image/upload/v1710784232/default_post_m8guti.jpg', upload_to='images/'),
        ),
    ]
