# Generated by Django 3.2.25 on 2024-03-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
    ]
